language: java
jdk:
- openjdk7
- oraclejdk8
- oraclejdk7
script: mvn install -B -V
notifications:
  slack:
    secure: VnWXoZIYDFYHzPvW+nrUMhkSVZhR2wiU6cuRJzM7ag+EG9TTYMn5nWK0fVxB6mlQvlf/qF6qVvN6pBsHyUsFcHVhaH1cy7fECMBIYjGUloLHUuYwnxaXEsvGGYVRXKPVy9eyCuL9vAwZLhAt/XcNEHcEwrYMGbabrGwc50J566MOsBUh+iSlNk5+aWylpJk/D8je5KV3mNiQSDh+e/s18LEeFeJ9RChxxo/lMz8EiaNUvmAiyylHuSb9DkTGGJzwShKMMB6iNTb8YtBI3NNEAR3H8l7hqYrffpbFTSVbXfaF3C1FVnd9eI4MmYEaX6YY0LMgSqIq1ApbMFu9qzOkx+KYNySz4RjsmpkjESxAaAf74nVJRYaplCI82s5P1082aAzPM3T+OWHQCbbBBeH2pbHLlaO2CD6wn4S0j4Dhx/HMonAPl4B8Mh3kA0qj/mIswsVMUWcC92grNACOYu5v33BUg9p6Y6s01LmH5UmAoWptXNq9DhhY9vOi35F6uw6diauksD1TLAJrex44UUn8jDN9+zto7Ii5TPKUfSmmfKt4deQolyxvKsVLWKR4+44No65Vo683Wj1EyPppfvX+FZhdbjJ29DB/s8qDSlgtTMUcbyuKfjcIsZ0QzuaqUdIiqsXJqIRav+gUU0wPr16Pbxdpe53nh2uPjvp8YviOdvA=
